### ISSUE TITLE
Remove Broken Mirror From Playroom

### ISSUE THREAD

**Issue by Stephanymtr** [bmhco/shared#18]
**We need to remove the broken mirror that is in the playroom ASAP.** 
Considering someone will take their time to remove the one broken mirror, should we take advantage of this opportunity and remove _all of them_ ? We have been talking about [changing the NIDO area](https://github.com/bmhco/shared/issues/4) to a warmer part of the room. I think this would be a good opportunity to make the first layout change in this room. 
_What do you all think?_ 

![IMG-4277](https://user-images.githubusercontent.com/91985721/213122895-3a6c5cf0-8f22-476a-b67a-43a02381b4b3.jpg)

![IMG-4244](https://user-images.githubusercontent.com/91985721/213122529-8c8e90a8-aff5-4327-8289-5d06fbd74af6.jpg)

**Comment by nelsonic** [comment]
@Stephanymtr thank you for opening this issue so we can take action on the broken mirror that has been temporarily patched using Duct Tape. This should be removed with the highest priority; like _now_! ⏳ 🔥

**Comment by nelsonic** [comment]
Going to use a razor blade (Stanley Knife) and cut-proof gloves to get this done _now_. ⏳

**Comment by nelsonic** [comment]
Miguel is already doing the tidy-up on the wall:

![C38B8CC2-3E82-458D-AC7E-3F36F04E6982](https://user-images.githubusercontent.com/194400/213150639-6c56930b-e209-4660-a9ab-35988ecb1043.jpeg)

keeping this assigned to me to monitor/manage as Miguel doesn’t have GitHub. ⏳

**Comment by nelsonic** [comment]
Plaster will be done in the next 5 mins but it will need to dry for a few hours before the paint can be applied. ⌛

**Comment by nelsonic** [comment]
first coat of paint is almost dry:

![31EBA9FF-46FC-48BC-9A50-81FF6414D075](https://user-images.githubusercontent.com/194400/213257234-45bc9b99-22d3-444f-bea2-bccdf2f72008.jpeg)

Miguel Will apply a second coat tomorrow m. 👌

**Comment by nelsonic** [comment]
The wall has been fully finished and it's like there was never anything there. 
Now we need to decide what is going to be in this North-West corner of the room 
to determine if we need to remove the mirrors & pull-to-stand bar https://github.com/dwyl/home/issues/184 which **`A1`** got a _lot_ of use out of!

**Comment by nelsonic** [comment]
Lowering priority as this is no longer a safety risk (broken glass).
