### ISSUE TITLE
Cracked green plastic bin; recycle? ♻️ 

### ISSUE THREAD

**Issue by nelsonic** [bmhco/shared#23]
the Joseph & Joseph plastic bin has been broken since last week and is just sitting in the kitchen corridor:

![A4BF7580-4010-46DD-91ED-8FB34CBD664C](https://user-images.githubusercontent.com/194400/217572154-ea3dc183-2d3d-4d71-85ed-c51746126295.jpeg)
![5841C62B-9966-491B-BAEC-D12B02128D85](https://user-images.githubusercontent.com/194400/217572161-bffc04e4-406a-4093-9f4a-d2857ef846a7.jpeg)

We’ve all bumped into it at least once and it’s just sitting there as a reminder.
What do you want to ***do*** with it, @iteles?
Can we just recycle it? Given that it’s not easy to fix … or do you still have hopes of reusing it for something? In which case where do you want to *store* it? 🤷‍♂️

**Comment by iteles** [comment]
The pieces fit exactly. We just need to get some super glue.

**Comment by nelsonic** [comment]
@iteles are you _sure_ you still have all the pieces and have a _use_ for this bin? Cause it's been empty for a _very_ long time. it _used_ to be our recycling bin in LDN but was always too small and impractical.

**Comment by nelsonic** [comment]
@iteles there is Epoxy resin and superglue in the basement you can use to mend this. Please go for it. 🙏

**Comment by nelsonic** [comment]
This was recycled last month as we realised we didn't have all the pieces. ♻️ 
Closing. ✅
