### ISSUE TITLE
Safe Location for Plants in the Garden🪴 

### ISSUE THREAD

**Issue by Stephanymtr** [bmhco/shared#24]
Currently, in the front garden, there are some plants living on the edge of the swimming pool. I understand that's the best area for them because of the amount of sunshine that area gets. However, they are within reach of a toddler. We should move them to a safer area or brainstorm a way to protect them from the little ones. 

_Where should we move them to?_

![plants](https://user-images.githubusercontent.com/91985721/217762391-38971845-32e5-4f83-962d-9b0972c2ac02.jpeg)

**Comment by nelsonic** [comment]
Ideally we would _plant_ these out on land https://github.com/dwyl/phase-three/issues/116 
but in the mean time we will move the plants to the west end of the pool so that they cannot be pulled down by children.

**Comment by Stephanymtr** [comment]
@nelsonic Do you want me to get this done this am ? 💪🏻

**Comment by nelsonic** [comment]
Yes, if you head outside you can get Miguel's help with it. 
However ... I've had a further thought on where we can store them so that:
a) they get more sunlight
b) they are out-of-the-way and not cluttering the front-garden area. 

Gotta do 09:30 standup meeting now.
But will be available around 09:50. Is that a good time for you?

**Comment by Stephanymtr** [comment]
Yes, let's do it. 👍🏻

**Comment by Stephanymtr** [comment]
Plants have been moved to the back of the house! 🪴 The front garden looks a lot more spacious now! thank you @nelsonic 

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/91985721/219356076-499bc293-2874-408c-b828-90d5daced494.png">

Miguel is working on the garden _today_ which explains why the tools and cables are on the edge of the pool. However, he will be done soon, and the area will be 100% safe for little ones to run around.

**Comment by nelsonic** [comment]
Glad we got this done only took a few mins to move everything and will look _much_ better! 🎉
