### ISSUE TITLE
Fixing the Samsung washing machine

### ISSUE THREAD

**Issue by iteles** [bmhco/shared#30]
The Samsung Ecobubble washing machine is perfect for the frequent small leads we will need for towels and cloths and also had a great quick wash function. It is reliably eco friendly/efficient too. 

However, for the last couple of months we'd haven't been able to use it because it shows a **4C** error on the screen part way into the wash cycle and we can't get past it (pressing play will only result in the error a couple of minutes later again). 

We have tried coming out the filter (accessible through the hatch of the front bottom right of the machine) many times but it makes no difference. 

It is out of warranty now but it's time to call in the professionals. 

@Stephanymtr Could you please call the Samsung Portugal customer service helpline, explain the issue and all what the orçamento is for a fix?

If it's less than €150, please book it for next week on a day you can come in to manage it. 
Maybe combine with a day that sofa cleaning can also be done 👌🏻

**Comment by Stephanymtr** [comment]
@iteles I called them and talked to Angelica - Numero de cliente: 2612498107

She asked me a couple of questions that I couldn't answer because I need access to the back of the washing machine. Do you think it would be possible to get Miguel to help bring the machine out of the shelf somehow?

Here is a list of things she asked me to check:

->verificar se o abastecimento de água está ligado/ não está congelado/ se a pressão da água é suficiente.
->verificar se as mangueiras não estão entupidas ou dobradas
->verificar se os filtros da malha estão limpos - estes filtros ficam na parte de trás onde está ligada a torneira com a máquina. 
-> verificar que a mangueira de água está devidamente ligada - para que não tenha fuga 


- I scheduled another phone call for 11 am, but they are available until 8 pm today. 
- If we are able to verify everything listed above, and the error persists, the next step is to call the closest centro tecnico to ask for a quote. 

What would you like me to do next ?

**Comment by nelsonic** [comment]
@Stephanymtr thanks for calling the support line.
If we can clear everything from the floor in the laundry room, 
Miguel and I can remove it from the shelf today. **`T25m`**
Once it's removed we can do the checks `Angelica` has suggested
**`then`** we @iteles can call back and follow-up with support. 🤞

**Comment by Stephanymtr** [comment]
Sound good!
FYI: I called the closest Assistência técnica oficial da Samsung to ask for a quote. They don't give quotes over the phone. They would need to come in to analyze the machine in person. The centro tecnico is Asteguima in Guimarães. https://goo.gl/maps/czXiAsoip7QR1Fhk6 They charge a 30 euros fee for deslocação.

**Comment by iteles** [comment]
I've asked Luis to organise with Miguel to bring the washing machine down tomorrow at the end of the day (after DT has done any washing needed) so it should be available for you on to run checks on Thursday @Stephanymtr 🤞

**Comment by Stephanymtr** [comment]
Ok. @nelsonic  Do you know if the water hose connected to the machine is long enough that I will be able to analyze if something is broken/bent/not connected while the machine is down on the floor ? Or will Luis and Miguel need to disconnect _everything_ for them to be able to bring the machine down?

Regardless, I will call the helpline tomorrow to help me do a thorough inspection. 

@iteles If we decide that technical assistance will be needed, can I schedule a visit ASAP or did you want to make that phone call to schedule a day/time that works best for you?

**Comment by Stephanymtr** [comment]
Luis and Miguel removed the machine. Miguel( and the Samsung agent ) helped me analyze the machine. Everything looks great. The hose is a bit burnt from the heat but works fine. ![image](https://user-images.githubusercontent.com/91985721/220882111-38c422d5-1228-4633-a871-48ed76df25d6.jpeg)

The cable had a superficial cut. We quickly fixed that with a tape.
![image](https://user-images.githubusercontent.com/91985721/220882361-0dd48895-e4f3-42cc-b133-ffa680d37d01.jpeg)
![image](https://user-images.githubusercontent.com/91985721/220882401-c72a268d-2b30-40cb-af9d-7f2904f78642.jpeg)

The hose's filter and machine's filter were cleaned. Not dirt blocking them.

![image](https://user-images.githubusercontent.com/91985721/220882642-8e79e08c-805b-4a02-bf93-4c543c1e96eb.jpeg)

![image](https://user-images.githubusercontent.com/91985721/220882706-9fd4336d-d626-4d82-8aac-7183a78d6629.jpeg)

The hose that connects to the machine looks brand new, not cuts or anything. We also checked water pressure. Works well. 
![image](https://user-images.githubusercontent.com/91985721/220882895-03b0c67f-d2c1-47a8-8365-db45a9fdec8a.jpeg)


Miguel believes is a problem on the inside of the machine more specifically on the "bomba de água".

**Comment by Stephanymtr** [comment]
I made the request. It will take 24 to 48 hrs for the centro técnico to call me back with an orçamento. We can accept it or not. 
If they come and see that’s it’s a motor problem, they will active the warranty. We would only have to pay for deslocação. 
If they come and see it’s another anomalia not related to the motor, then you would pay for their deslocação + mão de obra (if you decide you want their service) 
—-
Miguel mentioned he knows someone. 
Here is the person contact information: 966745876
Already called this number a few times, but nobody picked up yet.  
---
The machine is on the floor still. Please let me know if you want me to ask the boys to move it back to where it was or move it somewhere else. Thanks 

![image](https://user-images.githubusercontent.com/91985721/220884442-5458379f-98aa-478a-8dd9-550ed77b848e.jpeg)

**Comment by iteles** [comment]
DT _should have already finished all of her washing so it _should_ be fine to leave it (seeing as the technician will need it to be down on the ground anyway). 

Please ask her to call me when she arrives 👌🏻

**Comment by iteles** [comment]
The washing machine guy Miguel knew randomly showed up on our doorstep today because Miguel told him to come apparently.

He identified one big issue as being the drainage pump which wasn't working properly, not draining the water correctly and then causing issues with the water. This also meant our stuff was getting washed in dirty water which is why it wasn't washing properly.

We substituted that for €60.

He also suggested that it _sounded_ like the water pump wasn't quite working correctly but he couldn't be sure. 

We agreed we'll test the machine and he'll return (and I'll reopen this issue) if the error is still there.

**Comment by nelsonic** [comment]
@iteles did he replace the _tube_ that was mangled?

**Comment by iteles** [comment]
He didn't. I'll ask about doing that when he's next here.

**Comment by nelsonic** [comment]
Just want to know if I need to add a tube to my Leroy Merlin Shopping List... 🛒

**Comment by iteles** [comment]
Would you be the one to swap it out? I don't know how much of a job getting it to seal properly is.

**Comment by nelsonic** [comment]
@iteles went to Leroy Merlin. This wasn't on the list so didn't buy one. 
For future reference: they are easy to fit; they have a screw fitting on both ends with a rubber gasket.

**Comment by iteles** [comment]
👌🏻 Was only asking because you said you'd have to go back to LM today for more stuff.

**Comment by nelsonic** [comment]
If I could *not* go back to LM _ever_ again I would be soooo happy. 🙃 
I feel like I've been there _hundreds_ of times and should own *shares* in the biz ... 🙄 
Miguel went to LM to buy the remaining building materials. 💸
