### ISSUE TITLE
Paper strimmer

### ISSUE THREAD

**Issue by iteles** [bmhco/shared#45]
I owned a Fiskars strimmer which appears to have totally disappeared 😕 

We don't need a professional one that takes up loads of space, but having one is useful so we don't have to cut out cards and activities by hand.

This is the one I had and it worked super well and we'd want spare blades:
https://craftelier.com/pt-pt/tesoura-de-guilhotina-surecut-scrapbooking-fiskars.html

Also fancy one of these but not really necessary:
https://craftelier.com/pt-pt/catalog/product/view/id/26309/s/cortador-de-papel-de-cortador-de-plastico-fiskars/

**Comment by nelsonic** [comment]
@iteles did you end up ordering a `new` one or finding your _existing_ one? 💭

**Comment by iteles** [comment]
The laminator I ordered comes with a small one as part of the package:

https://amzn.eu/d/bEYi5XM
![image](https://user-images.githubusercontent.com/4185328/236508666-83c1abf0-aecf-48ec-8e84-a5351597173f.png)

Closing for now.
