### ISSUE TITLE
Broken Kinetic Sand Bucket

### ISSUE THREAD

**Issue by nelsonic** [bmhco/shared#46]
This bucket of kinetic sand has been on the kitchen counter for a while … ⏳

![IMG_4844](https://user-images.githubusercontent.com/194400/236136009-2e784e38-58c3-4510-b510-96233f25bb6f.jpeg)

@iteles where does it belong? 🤷‍♂️
What do you want to _do_ with it?

**Comment by Stephanymtr** [comment]
Hi! Sand has been packed away - just need A's help to separate the magnetic chips. Where do you want these buckets to live?

**Comment by iteles** [comment]
The attic seems so far away 😅 
Let's leave them in the arts and crafts area for now and see if Alex digs them out or not.

**Comment by Stephanymtr** [comment]
We have been using the plastic tupperware to pack away the kinetic sand. A1 has learned to put it away with a spoon after a couple of days of playing with it.
