### ISSUE TITLE
Chore: Replace broken string on Bones Ukulele

### ISSUE THREAD

**Issue by nelsonic** [bmhco/shared#51]
Bones ukulele Mod. SP420G

 ![IMG_7668](https://github.com/bmhco/shared/assets/194400/fc9b84b6-03f7-4745-8813-e2f01de1b1a9)
![IMG_7667](https://github.com/bmhco/shared/assets/194400/ba8262dd-cf8f-4e8e-8405-c8ea71993b43)

@Stephanymtr please call Salão Mozart (the store where we bought the Ukulele) and find out if they have strings for this ukulele in stock.

**Comment by nelsonic** [comment]
The exact model name is:
“Guitarlele Bones SP420G Abeto”
Because it has 6 strings as opposed to the 4 of a regular Ukulele.

CONTACTOS
Avenida da Liberdade, 72 
4715-037 Braga, Portugal
+351 253 273 547

**Comment by Stephanymtr** [comment]
Hi! A1 and I took the guitar to the shop this am. They charged us 2 euros for replacing the broken string. It's as good as new.

**Comment by nelsonic** [comment]
Thanks very much @Stephanymtr 🙏
