### ISSUE TITLE
Summer shoes for A

### ISSUE THREAD

**Issue by iteles** [bmhco/shared#59]
I've been meaning to open this issue for *weeks* but I'm always too tired at night and always feel guilty about using 'work time' for this and now here we are, way too late to do much about it.

It's getting so hot that it's basically a crime to get A to go outside in socks and tennis shoes.

NOTE: Here are the criteria for shoes that respect the correct development of the feet in case anyone was wondering:
+ Is the shape of the foot (i.e. is wide enough for the toes to not be scrunched - in itself very difficult to find, esp for girls - and the foot is not curved in the shoe to favour a 'correct shoe look')
+ There is no change in height from front to back (no mini heel, also difficult to find, especially in tennis shoes)
+ Is the right size: between 0,8cm and 1,2cm bigger than the foot length
  + The key is that this is the INSIDE length of the shoe, so the best way to judge is to take out the insole and measure that
  + When the shoe is 0,5cm bigger than the length of the foot, it's time to get new shoes
+ Flexible sole
+ Sole between 3 & 5mm ideally (we don't want to get too far away from barefoot or cushion the foot so much that walking correctly requires unconscious adjustment of the body or feet)
+ Flexible heel
+ For sandals, I'm also looking for _closed toe_ sandals to protect toes during climbing, slipping and falling and from excess dirt getting in. It also helps to hold the foot better in the shoe.

Here are the BEST options I found in sandals:

## Option 1: Froddo Barefoot Cognac

These are my absolute favourite but they will NOT arrive ahead of our trip.
https://www.caclesbarefoot.com/pt-pt/products/froddo-barefoot-sandalias-cognac
<img width="1133" alt="image" src="https://github.com/bmhco/shared/assets/4185328/b40ad846-99c1-4f45-a910-3842e668c08e">

Also available from here but also not 'in time': https://www.barefootnaboso.com/Sandals-193/FRODDO-SANDAL-D-VELCRO-Cognac

## Option 2: Tip Toey Joey Sand - in caramel

I'm a little uncertain about how the back of these doesn't come all the way down to meet the sole of the shoe so I'm not sure if it's a little less stable on the foot and is a mega potential to let in all sorts of debris.
HOWEVER, Tip Toey Joey is one of the most well known 'respectful footwear' companies in the world, so these should be safe developmentally.

Annoyingly, the brown ones are sold out in the bigger sizes EVERYWHERE. So this mustard yellow 'caramel' colour is the only one available, but I don't hate it _and_ there's a chance it will arrive tomorrow (sent DPD today, usually delivered next day but no guarantee):
https://madababystore.com/en/products/copia-de-sandalias-sand-verde-tip-toey-joey?variant=46863889334599
<img width="1119" alt="image" src="https://github.com/bmhco/shared/assets/4185328/7ddcfa45-c21a-4d57-a0a2-88a2be669715">

Also exist in green but not in A's size:
https://madababystore.com/en/products/copia-de-sandalias-sand-verde-tip-toey-joey

## An additional one: beach shoes
I think these would be great for rough beaches and gentle terrains - I was walking on a pebbly beach in Porto with A the other day and had to carry him half way back because both our feet hurt!

Two options here:
https://www.decathlon.pt/p/calcado-aquatico-bebe-aquashoes/_/R-p-346960?mc=8802102&c=AZUL
<img width="1082" alt="image" src="https://github.com/bmhco/shared/assets/4185328/9f744eab-e8c2-4877-a2f5-3d028ed0f85c">

Or:
https://madababystore.com/en/products/sandalias-de-praia-lassig?variant=46487027286343
<img width="1127" alt="image" src="https://github.com/bmhco/shared/assets/4185328/495ec577-09b1-479f-b49d-15093e6fd93b">

### Plastic sandals
Last year we had a set of these which were great for a 20 min walk but they have mini heel (are higher in the back than in the front) so should absolutely not be used for lots of walking.

My worry about getting these is that we might be tempted to use them as every day walking shoes because it's so hot (especially if they're the only thing we have ahead of our trip) and so we'd over-use them and have a detrimental effect:
https://madababystore.com/en/products/copia-de-sandalias-de-praia-igor-bege-tutete?variant=46835579584839

<img width="1058" alt="image" src="https://github.com/bmhco/shared/assets/4185328/fc553374-7d4e-49e4-a2c0-2d326e49952d">

## Also liked but no sizes left:
https://www.speechinlove.com/product-page/flexi-nens-sapato-madison-castanho
<img width="242" alt="image" src="https://github.com/bmhco/shared/assets/4185328/006c2f13-02a6-4c1f-995d-55cd4a595dea">
 
Lots more available from here (some even for me!) but would not arrive 'on time': https://www.barefootnaboso.com/childrens-barefoot-sandals/

## NOTES
We had some like this last year and @nelsonic hated them because that rim around the outside was a bit of a tripping hazard for `A`, though he walks a lot better now:
https://www.speechinlove.com/product-page/tip-toey-joey-sand%C3%A1lia-sandy-caramelo
<img width="987" alt="image" src="https://github.com/bmhco/shared/assets/4185328/09996963-c06d-4db7-bd32-c91dfcd8788d">

### Decathlon

This looks like the only option available from Decathlon for Summer and they're only available in Matosinhos so we can't go and see them. 
However, they look to me like they're nowhere near wide enough, the sole is too thick and possibly not flexible enough. 
I'd have to have them in hand to check:
https://www.decathlon.pt/p/calcado-de-ginastica-para-bebes-750-i-move-cn/_/R-p-328225?mc=8667776&c=AZUL
<img width="1329" alt="image" src="https://github.com/bmhco/shared/assets/4185328/85a4c71f-a301-4a7f-af27-d514bb8a57b9">
<img width="426" alt="image" src="https://github.com/bmhco/shared/assets/4185328/d4b08bec-02e9-4790-9bc0-8c678a8e9156">

**Comment by iteles** [comment]
@nelsonic My instinct is to just get the Decathlon water/beach shoes for now and then order my 'option 1' pick to arrive after our upcoming journey (but in time for summer).

Changed the priority here to p1 just because if we decide to go with this, we'll need to do a quick trip to Decathlon today or tomorrow.

**Comment by nelsonic** [comment]
Decathlon all-the-way. 
Don't forget that Decathlon totally exists where we're _going_: 
https://www.decathlon.ch/de/store-view/filiale-zurich-center-0070225302253
<img width="1753" alt="image" src="https://github.com/bmhco/shared/assets/194400/10143826-8d53-4992-b628-cfd96e9cc8af">

**Comment by iteles** [comment]
Good shout. Might actually be a nice 'run around post flights' break. 

![image](https://github.com/bmhco/shared/assets/4185328/1c5d2fc6-3f4c-48b8-bbb9-b5f3bfebba82)

**Comment by nelsonic** [comment]
Yeah, and you can check stock levels from here if needed.
I'm obvs happy to head to Decathlon _today_ after swimming if this is too much of a detour off our route on Wednesday.
Your call. 💭

**Comment by iteles** [comment]
We can get these at Decathlon in Lisbon but they are not the everyday open shoe we are needing for summer. 

Are you happy for me to also order option 1 and get it sent to Lisbon?
