### ISSUE TITLE
Inflatable chair cushion for A

### ISSUE THREAD

**Issue by iteles** [bmhco/shared#60]
Soon enough, A, like Kika, will no longer want to sit in a high chair but there won't always be cushions available to prop him up in a stable way at people's houses and never in restaurants. 

The Airbnb we will be staying in on our upcoming trip for example is likely to have one high chair which we'll need for 👶 

And in 2 years when 👶 gets to using it (and she may abandon the high chair sooner just before A because her legs may stop fitting through comfortably), A will probably no longer need it. 
One purchase, two kids 🤞

So I'm wondering whether this might be a wise purchase (I know of one person who has one and she uses it all the time and likes it):

https://www.twinklelittlestore.com/product/almofada-de-assento-or-ice-cream-rosa-8
![image](https://github.com/bmhco/shared/assets/4185328/6615c636-194f-48a0-9f11-933bc66c2c9e)
![image](https://github.com/bmhco/shared/assets/4185328/c027a6de-2b48-433e-b19b-2f1d78cd1595)
![image](https://github.com/bmhco/shared/assets/4185328/ca20b369-95e5-422f-b4e6-7b6972022a93)

Adding p1 in case we want it for the upcoming trip, will need to be ordered first thing Monday morning.

**Comment by nelsonic** [comment]
This feels like a manufacturer with excess capacity inventing a "product" 
and then marketing it to parents that have too much money ... 

From these images it looks like the pillow gives the child a `~15cm` boost.
<img width="1394" alt="inflatable-cushion" src="https://github.com/bmhco/shared/assets/194400/0966eb06-7440-46dc-a4ba-0fcd0dbe928d">

Also, FYI this ridiculous [Facebook](https://github.com/dwyl/learn-react/issues/23) messenger popover puts me off this retailer completely.

<img width="1394" alt="image" src="https://github.com/bmhco/shared/assets/194400/87abc61a-4467-4fc4-ab8d-d97bfea331bf">

Feels like we're just creating landfill by buying this. 💭 
When we can _easily_  use a firm pillow/cushion to achieve the same result at zero cost.
