### ISSUE TITLE
A Flauta Magica do Mozart na Casa da Musica

### ISSUE THREAD

**Issue by iteles** [bmhco/shared#99]
There are a couple of dates for this in late September/early October (29th Sept and 6th October I think, Sundays at 10h00). Looks like we should definitely do this with both kids (it's for ages 3 months to 6 years):

https://casadamusica.com/event/a-flauta-magica-do-mozart-2/?selected_session=24137

![Screenshot 2024-09-05 at 16 53 08](https://github.com/user-attachments/assets/76358d88-a8f1-4a91-aa0d-7e9857b58880)

I'm thinking Sunday 6th October would be good as we won't *just* be back from the Algarve.

Book it?

**Comment by nelsonic** [comment]
Loos fun. Book for sure. 👌

**Comment by iteles** [comment]
Just checking with my uncle to see if he's expecting us on Sunday 6th for anything (4 th October is his birthday - Didi) and will book.

**Comment by iteles** [comment]
There are now a whole bunch more dates so I'm thinking:
Because there is a small possibility that Vicente will have a birthday lunch on the 5th October in Porto and we already have Tio Didi's birthday on Friday 4th and Titi from the forest's birthday on Saturday 5th as well, I will book for the following weekend on the Sunday (10th October):
<img width="114" alt="image" src="https://github.com/user-attachments/assets/4b0cb239-ceed-451d-9967-ed2a12de76ea">

**Comment by nelsonic** [comment]
Leaking a lot of personal/family details in this one comment, Inês. Please consider deleting. 💭 
Sure, alternative dates are great they give us more [choice](https://en.wikipedia.org/wiki/Overchoice) ... 🙃

**Comment by iteles** [comment]
Booking for 17th November at 10h00 unless you have an objection.

**Comment by nelsonic** [comment]
I _really_ feel like `A2` has not had the same level of musical exposure as `A1` did ... 
Wish we could find another "Gui" to guide her.

**Comment by iteles** [comment]
I've actually tried but for her age it's tough. 

I sing to and with her multiple times a day every day. We go through the musical scale in Portuguese every day (forward and back) and I do little rhythm games with her whenever I can. 
But I need to set up a musical 'curriculum' so others can do things too. 

Between now and Xmas we have 3 kids concerts (interactive), this musical and Pipa's choir performance. 
She was my driving force.

**Comment by iteles** [comment]
There was a glitch last week which didn't let me book tickets and now the only availability is the 1st or the 8th of December. On the 1st we have Pipa's choir thing and it'll be too much for the kids to sit through 2 performances in one day so I'm going with the 8th December. At 11h30.

[Bilhetes 9cada3ce-b8a7-471d-a33f-ef13dea1c696.pdf](https://github.com/user-attachments/files/17362987/Bilhetes.9cada3ce-b8a7-471d-a33f-ef13dea1c696.pdf)

Added to the calendar. Closing for clarity.
